[package]
name = "gun-rust-wasm-play"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rusty-gun = { path = "./submodules/gun-rs-wasm" }
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
yew = "0.19.3"
